ENH: CPU feature check for AMD and Intel CPUs
Builds on @skarekrow's PR #153 to check for AMD CPUs and handle
when an Intel 5500 Xeon series CPU (Only ones missing "UG" CPU
feature) are used.

This is needed for underlying bhyve support.

diff --git a/iohyve b/iohyve
--- a/iohyve
+++ b/iohyve
@@ -5,9 +5,16 @@
 # Set proper path thanks to iocage
 PATH=${PATH}:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
 
-if ! $(cat /var/run/dmesg.boot | egrep -q 'VT-x|EPT') ; then
-   echo "Your CPU does not seem to support bhyve."
-   exit 1 
+# Check to see if CPU is compatible with bhyve
+if [ $( cat /var/run/dmesg.boot | grep 'POPCNT' ) ]; then
+	if [ -n "$( cat /var/run/dmesg.boot | grep 'CPU:' | grep 'Intel' )" ] && [ -z "$( cat /var/run/dmesg.boot | grep 'VT-x:' | grep 'UG' )" ]; then
+		echo "Your CPU does not seem to fully support bhyve. Missing UG feature on Intel CPU, please upgrade to 5600 series."
+		exit 1
+	fi
+else
+	echo "Your CPU does not seem to support bhyve."
+	echo "For AMD CPUs this means RVI. For Intel CPUs this means EPT."
+	exit 1 
 fi
 
 # Check if libs are available (stolen from iocage)
