add rmsnap function

diff --git a/lib/ioh-zfs b/lib/ioh-zfs
--- a/lib/ioh-zfs
+++ b/lib/ioh-zfs
@@ -137,6 +137,33 @@ __zfs_rollguest() {
 	fi
 }
 
+# Remove a snap
+__zfs_rmsnap() {
+	local flagone="$2"
+	local flagtwo="$3"
+	if [ $flagone = "-f" ]; then
+		if [ -z "$flagtwo" ]; then
+			printf "missing argument\nusage:\n"
+			printf "\trmsnap [-f] <name>@<snapname>\n"
+			exit 1
+		fi
+		echo "Removing snapshot $flagtwo"
+		echo "I hope it was a snapshot and not a guest."
+		local pool="$(zfs list -t snapshot | cut -d '/' -f-3 | grep "$flagtwo" | head -n1 | cut -f1 -d/)"
+		zfs destroy -r $pool/iohyve/$flagtwo
+	else
+		local pool="$(zfs list -t snapshot | cut -d '/' -f-3 | grep "$flagone" | head -n1 | cut -f1 -d/)"
+		echo "Warning: if you supply a guestname and not a guestname@snapname, you will destroy the guest."
+		read -p "Are you sure you want to remove $flagone [Y/N]? " an </dev/tty
+		case "$an" in
+			y|Y) zfs destroy -r $pool/iohyve/$flagone
+			;;
+			*) echo "Not removed..."
+			;;
+		esac
+	fi
+}
+
 # Clone a guest
 __zfs_cloneguest() {
 	local flag="$2"
